---
title: "group_document"
format: html
editor: visual
---

## s203556

hej søde piger \<3

```{r}
x <- c("s203556", "s203542", "s204570", "s194692", "s205803")
```

### New feature

hej igen \<3 i er søde

## s203542

Hej mit navn er Cecille. I er søde alle sammen!

<<<<<<< HEAD
`{r} #code uden nogen code, men det er en chunk}`

`{r} (203556+203542+204570+205803+194692)/5}`

### New feature

hello new feature is cool!
=======
<<<<<<< HEAD
`{r} #code uden nogen code, men det er en chunk}`

`{r} (203556+203542+204570+205803+194692)/5}`
=======
```{r}
#code uden nogen code, men det er en chunk
```
>>>>>>> 797eb6cdce76c10e50cfa74927eb91fcbb1a44e7
>>>>>>> ed8e0ad5ace1d869c762e991a6d2226c2b701f93

```{r}
(203556+203542+204570+205803+194692)/5
```

## s204570

hej

```{r}
2+2
```

## s205803

Fem flade flødeboller på et *flot* fladt flødebollefad

```{r}
5^5
```

```{r}
203556+203542+204570+205803+194692
```

## s194692

Hey hey, Agnes here, adding some text

and some code...

```{r}
Agnes <- c(185, 22, 12, 1999)
```

lalala

```{r}
# more code
x <- "hey"
print(x)
```
